remote_theme: "mmistakes/minimal-mistakes@4.15.2"
#theme: minimal-mistakes-jekyll
minimal_mistakes_skin: dark

paginate: 5 # amount of posts to show
paginate_path: /page:num/

# Site Settings
locale: "en-UK"
title: "R Musing"

name: "Mike L. Smith"
twitter:
  username: "grimbough"

# Site Author
author:
  name     : "Mike L. Smith"
  avatar   : "https://s.gravatar.com/avatar/596fcf79708da70488a96ac9441c98fc?s=120"
  bio      : "Iâ€™m a bioinformatician working at EMBL Heidelberg as part of the German Network for Bioinformatics Infrastructure (de.NBI)."
  location : "Heidelberg, DE"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/grimbough"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/grimbough" 

plugins:
  - jekyll-redirect-from
  - jekyll-include-cache
  - jekyll-feed

# Reading Files
include:
  - _pages
exclude:
  - "*.Rproj"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: true
